
# Need to compile core lib features from scratch for target host instead of pulling in pre-built ones
# that only support a specific set of targets
[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = ".cargo/x86_64-op-sys.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"